// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026-02-06, 7:58:26 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/plugins/**/*.{js,ts,mjs}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/composables/**/*.{js,ts,mjs}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/utils/**/*.{js,ts,mjs}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varma/Documents/Code/smart-meal-planner/Smart-Meal-Planner/App/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;